//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NirSoftNetTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NirSoftNetTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 35913201,3GNET,G Series G528,,
        ///35454103,3Q,H2+,,
        ///35530403,3Q,H5,,
        ///35239303,3Q,P2890,,
        ///35276703,3Q,S3+,,
        ///35276603,3Q,T33+,,
        ///35232300,4P Mobile Data Processing,DAT500,,
        ///35233800,4P Mobile Data Processing,DAT500,,
        ///35927500,4P,5s,,
        ///01017900,@Road,iWM 3150,,
        ///35096322,A P Systems,AT 420,,
        ///35961103,A-Phone,A88/A99/A66/A100,,
        ///35096300,ABB VSM,Veriphon D45-1P,,
        ///49002400,ABB,VSMVeriphon D45-2H,,
        ///35622703,ABEO,BK66,,
        ///35578503,ACE,H5,,
        ///35647503,ACE,H9,,
        ///35729103,ACE,M11,,
        ///35778403,ACE,Z9,,
        ///35169704,ACE,Z9700/Z9630,,
        ///35 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string imeidb1 {
            get {
                return ResourceManager.GetString("imeidb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Osmocom TAC database under CC-BY-SA v3.0 (c) Harald Welte 2016
        ///tac,name,name,contributor,comment,gsmarena,gsmarena,aka
        ///35675904,Oppo,N1,Kévin Redon,,http://www.gsmarena.com/oppo_n1-5724.php,http://www.gsmarena.com/oppo-phones-82.php,
        ///49013920,Nokia,1610,OsmoDevCon 2014,,,http://www.gsmarena.com/nokia-phones-1.php,&quot;1610+,1611,1611+,NHE-5NX&quot;
        ///49502220,Nokia,1620,OsmoDevCon 2014,,,http://www.gsmarena.com/nokia-phones-1.php,NHK-5NY
        ///35250500,Nokia,6820,OsmoDevCon 2014,,http://www.gsmarena.com/nokia_6820-565.p [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string imeidb2 {
            get {
                return ResourceManager.GetString("imeidb2", resourceCulture);
            }
        }
    }
}
